app:
  telegram-token: "6922990872:AAHPWT6cYPr1-LBLs8RU4zGqiQJo_mFMUfg"

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
